Onset/Models/REPORT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORT()
        {
            this.REPORTUSERS = new HashSet<REPORTUSER>();
        }
    
        public int REPORT_ID { get; set; }
        public string REPORT_BODY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTUSER> REPORTUSERS { get; set; }
    }
}

Onset/Models/ROOM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.CHATMESSAGES = new HashSet<CHATMESSAGE>();
            this.CHATROOMS = new HashSet<CHATROOM>();
        }
    
        public int ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHATMESSAGE> CHATMESSAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHATROOM> CHATROOMS { get; set; }
    }
}

Onset/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Onset.Models;
using Onset.Models.ProfileModel;
using Onset.Models.DashboardModel;

namespace Onset.Controllers
{
    public class DashboardController : Controller
    {
        ONSETDBEntities db = new ONSETDBEntities();

        public ActionResult Index()
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            string email = Session["Email"].ToString();
            string usertype = Session["UserType"].ToString();

            DashboardModel dashInfo = generateDashboardInfo();

            IndexModel info = new IndexModel();
            info.NAME = dashInfo.NAME;
            info.USERTYPE = dashInfo.USERTYPE;
            info.PROFILEPIC = dashInfo.PROFILEPIC;

            info.DASHINFO = dashInfo;

            if (usertype == "Manager")
            {
                var check = db.MANAGERS.Where(u => u.MANAGER_EMAIL == email).FirstOrDefault();
                int id = check.MANAGER_ID;

                var tasklist = db.TASKMANAGERS.Where(u => u.MANAGER_ID == id).ToList();

                var taskinfo = new List<TASK>();
                var empinfo = new List<EMPLOYEE>();
                var propics = new List<String>();
                var perc = new List<float>();
                var userids = new List<int>();

                foreach (var e in tasklist)
                {
                    int taskid = e.TASK_ID;

                    var taskok = db.TASKS.Where(u => u.TASK_ID == taskid).FirstOrDefault();
                    if (taskok.TASK_DEADLINE.Year < System.DateTime.Now.Year) continue;
                    if (taskok.TASK_DEADLINE.Month < System.DateTime.Now.Month) continue;
                    if (taskok.TASK_DEADLINE.Day < System.DateTime.Now.Day && taskok.TASK_DEADLINE.Month == System.DateTime.Now.Month) continue;

                    taskinfo.Add(taskok);

                    var ep = db.TASKEMPLOYEES.Where(u => u.TASK_ID == taskid).FirstOrDefault();
                    var temp_emp = db.EMPLOYEES.Where(u => u.EMPLOYEE_ID == ep.EMPLOYEE_ID).FirstOrDefault();

                    empinfo.Add(temp_emp);

                    var temp_email = temp_emp.EMPLOYEE_EMAIL;

                    var temp_user = db.USERS.Where(u => u.USER_EMAIL == temp_email).FirstOrDefault();

                    userids.Add(temp_user.USER_ID);

                    var temp_pic = db.USERPICS.Where(u => u.USER_ID == temp_user.USER_ID).FirstOrDefault();

                    if (temp_pic != null)
                    {
                        propics.Add("/Upload/ProfilePicture/" + temp_pic.USER_PIC);
                    } else
                    {
                        propics.Add("https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp");
                    }

                    var progresses = db.TASKPROGRESSES.Where(u => u.TASK_ID == taskid).ToList();
                    float percent = 0f;

                    if (progresses != null)
                    {
                        foreach (var f in progresses)
                        {
                            int proid = f.PROGRESS_ID;
                            var chk = db.PROGRESSES.Where(u => u.PROGRESS_ID == proid).FirstOrDefault();

                            percent += chk.PROGRESS_PERCENTAGE;
                        }
                    }

                    perc.Add(percent);
                }

                info.TASKS = taskinfo;
                info.EMPS = empinfo;
                info.PROPICS = propics;
                info.PERCENTS = perc;
                info.USERIDS = userids;
            } else
            {
                var check = db.EMPLOYEES.Where(u => u.EMPLOYEE_EMAIL == email).FirstOrDefault();
                int id = check.EMPLOYEE_ID;

                var tasklist = db.TASKMANAGERS.Where(u => u.MANAGER_ID == id).ToList();

                var taskinfo = new List<TASK>();
                var maninfo = new List<MANAGER>();
                var propics = new List<String>();
                var perc = new List<float>();
                var userids = new List<int>();

                foreach (var e in tasklist)
                {
                    int taskid = e.TASK_ID;

                    var taskok = db.TASKS.Where(u => u.TASK_ID == taskid).FirstOrDefault();
                    if (taskok.TASK_DEADLINE.Year < System.DateTime.Now.Year) continue;
                    if (taskok.TASK_DEADLINE.Month < System.DateTime.Now.Month) continue;
                    if (taskok.TASK_DEADLINE.Day < System.DateTime.Now.Day && taskok.TASK_DEADLINE.Month == System.DateTime.Now.Month) continue;

                    taskinfo.Add(taskok);

                    var ep = db.TASKMANAGERS.Where(u => u.TASK_ID == taskid).FirstOrDefault();
                    var temp_emp = db.MANAGERS.Where(u => u.MANAGER_ID == ep.MANAGER_ID).FirstOrDefault();

                    maninfo.Add(temp_emp);

                    var temp_email = temp_emp.MANAGER_EMAIL;

                    var temp_user = db.USERS.Where(u => u.USER_EMAIL == temp_email).FirstOrDefault();

                    userids.Add(temp_user.USER_ID);

                    var temp_pic = db.USERPICS.Where(u => u.USER_ID == temp_user.USER_ID).FirstOrDefault();

                    if (temp_pic != null)
                    {
                        propics.Add("/Upload/ProfilePicture/" + temp_pic.USER_PIC);
                    }
                    else
                    {
                        propics.Add("https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp");
                    }

                    var progresses = db.TASKPROGRESSES.Where(u => u.TASK_ID == taskid).ToList();
                    float percent = 0f;

                    if (progresses != null)
                    {
                        foreach (var f in progresses)
                        {
                            int proid = f.PROGRESS_ID;
                            var chk = db.PROGRESSES.Where(u => u.PROGRESS_ID == proid).FirstOrDefault();

                            percent += chk.PROGRESS_PERCENTAGE;
                        }
                    }

                    perc.Add(percent);
                }

                info.TASKS = taskinfo;
                info.MANS = maninfo;
                info.PROPICS = propics;
                info.PERCENTS = perc;
                info.USERIDS = userids;
            }

            return View(info);
        }

        [HttpGet]
        public ActionResult AddTask ()
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            if (Session["UserType"].ToString() != "Manager")
            {
                return RedirectToAction("Index");
            }

            AddTaskModel list = new AddTaskModel();
            list.CATEGORIES = new List<SelectListItem>();

            list.CATEGORIES.Add(new SelectListItem() { Text = "UI Design", Value = "UI Design", Selected = true });
            list.CATEGORIES.Add(new SelectListItem() { Text = "Bug Fix", Value = "Bug Fix", Selected = false });
            list.CATEGORIES.Add(new SelectListItem() { Text = "Add Feature", Value = "Add Feature", Selected = false });

            var email = Session["Email"].ToString();

            var org = db.MANAGERS.Where(u => u.MANAGER_EMAIL == email).FirstOrDefault().MANAGER_ORGANIZATION;

            List<EMPLOYEE> le = db.EMPLOYEES.Where(u => u.EMPLOYEE_ORGANIZATION == org).ToList();

            list.EMPLOYEES = new List<SelectListItem>();
            bool isf = true;

            foreach (EMPLOYEE e in le)
            {
                var nam = e.EMPLOYEE_FIRSTNAME + " " + e.EMPLOYEE_LASTNAME;
                var id = e.EMPLOYEE_ID;

                if (isf)
                {
                    list.EMPLOYEES.Add(new SelectListItem() { Text = nam, Value = id.ToString(), Selected = true });
                } else
                {
                    list.EMPLOYEES.Add(new SelectListItem() { Text = nam, Value = id.ToString(), Selected = false });
                }
            }

            string usertype = Session["UserType"].ToString();
            DashboardModel dashInfo = generateDashboardInfo();

            list.NAME = dashInfo.NAME;
            list.USERTYPE = dashInfo.USERTYPE;
            list.PROFILEPIC = dashInfo.PROFILEPIC;

            list.DASHINFO = dashInfo;

            return View(list);
        }

        [HttpPost]
        public ActionResult AddTask (AddTaskModel info)
        {
            string name = info.TASKNAME;
            string cat = info.CATEGORY;
            int empid = info.EMPLOYEEID;
            string des = info.DESCRIPTION;
            var date = info.DEADLINE;

            TASK newtask = new TASK()
            {
                TASK_NAME = name,
                TASK_DEADLINE = date,
                TASK_DESCRIPTION = des,
                TASK_CATEGORY = cat
            };

            db.TASKS.Add(newtask);

            db.SaveChanges();

            int id = newtask.TASK_ID;

            db.TASKEMPLOYEES.Add(new TASKEMPLOYEE() {
                EMPLOYEE_ID = empid,
                TASK_ID = id
            });

            db.SaveChanges();

            var email = Session["Email"].ToString();

            var man = db.MANAGERS.Where(u => u.MANAGER_EMAIL == email).FirstOrDefault();
            int manid = man.MANAGER_ID;

            db.TASKMANAGERS.Add(new TASKMANAGER()
            {
                MANAGER_ID = manid,
                TASK_ID = id
            });

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditTask (int? id)
        {
            if (Session["Email"] == null)
            {

Onset/Views/Dashboard/AddProgress.cshtml
@model Onset.Models.DashboardModel.AddProgessModel

@{
    Layout = null;
    bool is_manager = Model.USERTYPE == "Manager";
    string pic = "https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp";

    if (Model.PROFILEPIC != null)
    {
        pic = Model.PROFILEPIC;
    }
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Add Progress</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
          rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="~/Content/style.css" rel="stylesheet" />
</head>


<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner"
             class="show bg-light position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3 bg-light">
            <nav class="navbar bg-light">
                <a href="/Dashboard/Index/" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">
                        <i class="fa fa-user-edit me-2"></i>OnSet
                    </h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle"
                             src="@pic" alt="avatar 1"
                             style="width: 40px; height: 40px" />
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                        </div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">@Model.NAME</h6>
                        <span>@Model.USERTYPE</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="/Dashboard/Index" class="nav-item nav-link active"><i class="fa fa-laptop me-2"></i>Dashboard</a>
                    <a href="/Dashboard/ViewTable" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
                    <a href="/Dashboard/Rooms" class="nav-item nav-link"><i class="fa fa-bell me-2"></i>Message</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notification</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a class="notification-a">
                                <h6 class="fw-normal mb-0">Task</h6>
                                @{
                                    for (int i = 0; i < Model.DASHINFO.TASKS.Count && i < 2; i++)
                                    {
                                        <small>@Model.DASHINFO.TASKS[i].TASK_NAME</small><br />
                                        <small style="font-size:12px">@Model.DASHINFO.TASKS[i].TASK_CATEGORY</small><br />
                                    }
                                }
                            </a>
                            <hr class="dropdown-divider" />
                            <a class="notification-a">
                                <h6 class="fw-normal mb-0">Event</h6>
                                @{
                                    for (int i = 0; i < Model.DASHINFO.EVENTS.Count && i < 2; i++)
                                    {
                                        <small>@Model.DASHINFO.EVENTS[i].EVENT_NAME</small><br />
                                        <small style="font-size:12px">@Model.DASHINFO.EVENTS[i].EVENT_CATEGORY</small><br />
                                    }
                                }
                            </a>

                            <hr class="dropdown-divider" />
                            <a href="/Dashboard/Notification/" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2"
                                 src="@pic" alt="avatar 1"
                                 style="width: 40px; height: 40px" />
                            <span class="d-none d-lg-inline-flex">@Model.NAME</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            @Html.ActionLink("My Profile", "ViewProfile", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Log Out", "Logout", "Auth", null, new { @class = "dropdown-item" })
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <!-- Blank Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row bg-table rounded align-items-center justify-content-center mx-0">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-table rounded h-100 p-4">
                            @using (Html.BeginForm("AddProgress", "Dashboard", FormMethod.Post, new
                            {
                                enctype = "multipart/form-data"
                            }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="d-flex align-items-center justify-content-between mb-4">
                                    <h6 class="mb-0">Progess</h6>
                                </div>
                                <div class="row">
                                    <div class="d-flex col-md-6 mb-2">
                                        <label>Task</label>
                                    </div>
                                    <div class="form-floating d-flex col-md-6 mb-2">

                                        @Html.DropDownListFor(m => m.TASKID, Model.TASKS, new { @class = "form-select", @id = "floatingSelect" })

                                    </div>

                                    <div class="d-flex col-md-6 mb-2">
                                        <label>Description</label>
                                    </div>
                                    <div class="form-floating d-flex col-md-6 mb-2">
                                        @Html.TextAreaFor(m => m.DESCRIPTION, 0, 0, new { @class = "form-control", @id = "floatingTextarea", @style = "height:150px" })
                                        <label for="floatingTextarea">Description</label>
                                    </div>

                                    <div class="d-flex col-md-6 mb-2">
                                        <label>Percent</label>
                                    </div>
                                    <div class="form-floating d-flex col-md-6 mb-2">
                                        @Html.TextBoxFor(m => m.PERCENT, new { @class = "form-control", @id = "floatingInput", @type = "number" })
                                        <label for="floatingInput">Percent</label>
                                    </div>

                                    <div class="d-flex col-md-6 mb-2">
                                        <label>File</label>
                                    </div>
                                    <div class="form-floating d-flex col-md-6 mb-2">
                                        <input type="file" class="form-control bg-dark" name="PROGRESSFILE" style="padding-top: 6px; padding-bottom: 6px; height: auto;">
                                    </div>
                                    <div class="d-flex mb-1">
                                        <button type="submit" class="btn btn-primary">Upload</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <!-- Blank End -->
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-table rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="/Dashboard/Index/">OnSet</a>, All Right Reserved.
                        </div>
                        <!--<div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        <!--Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                <br />Distributed By:
                <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
              </div>-->
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <script>
    $('.select2').select2();
    </script>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart/chart.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/Scripts/main.js"></script>
</body>


</html>

Onset/Views/Dashboard/CreateToDoList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateToDoList</title>
</head>
<body>
    <script>
        window.close();
    </script>
</body>
</html>